backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: 'Settings'
    name: 'settings'
    files:
      - label: 'Contact Info'
        name: 'contact_info'
        file: site/settings/contact_info.json
        fields:
          - { label: 'Phone', name: 'phone', widget: 'string' }
          - { label: 'Email', name: 'email', widget: 'string' }
      - label: 'Hours'
        name: 'hours'
        file: site/settings/hours.json
        fields:
          - {
              label: 'Mon',
              name: 'mon',
              widget: 'string',
              hint: 'example: 8am-11pm',
            }
          - { label: 'Tues', name: 'tues', widget: 'string' }
      - label: 'Gallery'
        name: 'gallery'
        file: site/settings/gallery.json
        media_folder: '/{{media_folder}}/gallery'
        fields:
          - label: 'GalleryImage'
            name: 'gallery_image'
            widget: 'list'
            fields:
              - { label: Image, name: image, widget: image }
              - { label: Description, name: description, widget: string }
