backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - label: 'Site Configuration'
    name: 'site_config'
    files:
      - label: 'Contact Info'
        name: 'contact_info'
        file: site/contact_info/index.json
        fields:
          - { label: 'Phone', name: 'phone', widget: 'string' }
          - { label: 'Email', name: 'email', widget: 'string' }
          - { label: 'Street', name: 'street', widget: 'string' }
          - {
              label: 'City State Zip',
              name: 'city_state_zip',
              widget: 'string',
              hint: 'example: Cody, WY 82414',
            }
          - { label: 'Twitter', name: 'twitter', widget: 'string' }
          - { label: 'Instagram', name: 'instagram', widget: 'string' }
          - { label: 'Facebook', name: 'facebook', widget: 'string' }
          - { label: 'LinkedIn', name: 'linkedin', widget: 'string' }
      - label: 'Hours'
        name: 'hours'
        file: site/hours/index.json
        fields:
          - { label: 'Monday', name: 'monday', widget: 'string' }
          - { label: 'Tuesday', name: 'tuesday', widget: 'string' }
          - { label: 'Wednesday', name: 'wednesday', widget: 'string' }
          - { label: 'Thursday', name: 'thursday', widget: 'string' }
          - { label: 'Friday', name: 'friday', widget: 'string' }
          - { label: 'Saturday', name: 'saturday', widget: 'string' }
          - { label: 'Sunday', name: 'sunday', widget: 'string' }
      - label: 'Gallery'
        name: 'gallery'
        file: site/gallery/index.json
        media_folder: 'images/'
        fields:
          - label: 'Gallery Images'
            name: 'gallery_images'
            widget: 'list'
            fields:
              - { label: 'Image', name: 'image', widget: image }
              - { label: 'Description', name: 'description', widget: string }
      - label: 'Testimonials'
        name: 'testimonials'
        file: site/testimonials/index.json
        fields:
          - label: 'Testimonial'
            name: 'testimonial'
            widget: 'list'
            fields:
              - { label: 'Name', name: 'name', widget: string }
              - { label: 'Text', name: text, widget: text }
