backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - label: 'Site Configuration'
    name: 'site_config'
    files:
      - label: 'Contact Info'
        name: 'contact_info'
        file: site/contact_info/index.json
        fields:
          - { label: 'Phone', name: 'phone', widget: 'string' }
          - { label: 'Email', name: 'email', widget: 'string' }
      - label: 'Hours'
        name: 'hours'
        file: site/hours/index.json
        fields:
          - {
              label: 'Mon',
              name: 'mon',
              widget: 'string',
              hint: 'example: 8am-11pm',
            }
          - { label: 'Tues', name: 'tues', widget: 'string' }
      - label: 'Gallery'
        name: 'gallery'
        file: site/gallery/index.json
        media_folder: 'images/'
        fields:
          - label: 'GalleryImage'
            name: 'gallery_image'
            widget: 'list'
            fields:
              - { label: Image, name: image, widget: image }
              - { label: Description, name: description, widget: string }
